# Generated by Django 4.0.3 on 2022-04-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='dercripsion',
            new_name='descripsion',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='dercripsion_html',
            new_name='descripsion_html',
        ),
    ]
